[build]
  command = "npm run build"  
  publish = "src"

[context.production]
  command = "npm run start"  
  environment = {
    NODE_ENV = "production",
  }

[context.deploy-preview]
  command = "npm run start"  
  environment = {
    NODE_ENV = "preview",
  }