[context.production]
  command = "npm run start"
  environment = {
    NODE_ENV = "production"
  }

[context.deploy-preview]
  command = "npm run start"
  environment = {
    NODE_ENV = "preview"
  }
  [build]
  command = "npm run build" # Replace with your build command
  publish = "src/" 